import type { AgentAdapterDescriptor } from "./types";

export const adapterRegistry: AgentAdapterDescriptor[] = [
  {
    id: "codex-cli",
    displayName: "Codex CLI",
    vendor: "openai",
    kind: "native_cli",
    transport: "local process / structured event stream",
    executable: "codex",
    defaultRole: "executor",
    trustBoundary: "local_runner",
    capabilities: {
      readFiles: true,
      writeFiles: true,
      runCommands: true,
      streamEvents: true,
      resumeSession: true,
      structuredOutput: true,
    },
  },
  {
    id: "claude-code",
    displayName: "Claude Code",
    vendor: "anthropic",
    kind: "native_cli",
    transport: "local process / JSON envelope",
    executable: "claude",
    defaultRole: "context",
    trustBoundary: "local_runner",
    capabilities: {
      readFiles: true,
      writeFiles: true,
      runCommands: true,
      streamEvents: true,
      resumeSession: true,
      structuredOutput: true,
    },
  },
  {
    id: "openhands-agent-server",
    displayName: "OpenHands Agent Server",
    vendor: "openhands",
    kind: "openhands",
    transport: "REST + WebSocket",
    defaultRole: "optional",
    trustBoundary: "remote_runtime",
    capabilities: {
      readFiles: true,
      writeFiles: true,
      runCommands: true,
      streamEvents: true,
      resumeSession: true,
      structuredOutput: true,
    },
  },
  {
    id: "acp-agent",
    displayName: "ACP agent",
    vendor: "varies",
    kind: "acp",
    transport: "ACP v1",
    defaultRole: "optional",
    trustBoundary: "local_runner",
    capabilities: {
      readFiles: true,
      writeFiles: true,
      runCommands: true,
      streamEvents: true,
      resumeSession: true,
      structuredOutput: true,
    },
  },
];
